"""campaigns.short_id, the human-readable RC36-NN identifier

B20 identifier model: today a campaign is only addressable by its 36-char
UUID, which is not "short and autogenerated. Human-readable" (03-IDENTIFIER-
MODEL.md). Additive per that doc's migration note: the UUID stays the
primary key and foreign-key target, this is a second, unique, indexed
column used only for display and search. Existing campaigns are backfilled
in creation order so the oldest campaign becomes RC36-01.

Revision ID: 1364a83bb0b4
Revises: 4e9b2765d18c
Create Date: 2026-09-13 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1364a83bb0b4'
down_revision: Union[str, Sequence[str], None] = '4e9b2765d18c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'campaigns',
        sa.Column('short_id', sa.String(length=20), nullable=True),
    )
    op.create_index(
        'ix_campaigns_short_id', 'campaigns', ['short_id'], unique=True,
    )

    connection = op.get_bind()
    rows = connection.execute(
        sa.text('SELECT id FROM campaigns ORDER BY created_at ASC')
    ).fetchall()
    for position, row in enumerate(rows, start=1):
        connection.execute(
            sa.text('UPDATE campaigns SET short_id = :short_id WHERE id = :id'),
            {'short_id': f'RC36-{position:02d}', 'id': row[0]},
        )


def downgrade() -> None:
    op.drop_index('ix_campaigns_short_id', table_name='campaigns')
    op.drop_column('campaigns', 'short_id')
