"""phase_e_challenge_findings

Revision ID: 1e9e5fabd527
Revises: 42eb3fd3b075
Create Date: 2026-09-10 14:32:20.256107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9e5fabd527'
down_revision: Union[str, Sequence[str], None] = '42eb3fd3b075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenge_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_key', sa.String(length=128), nullable=False),
    sa.Column('check', sa.Enum('UNSUPPORTED_CONCLUSION', 'INCONSISTENT_SCORING', 'MISSING_EVIDENCE', 'WEAK_EVIDENCE', 'CONTRADICTION', 'WEIGHTING_ANOMALY', 'OUTLIER_RECOMMENDATION', name='challengecheck', native_enum=False, length=40), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'LOW', 'MEDIUM', 'HIGH', name='challengeseverity', native_enum=False, length=16), nullable=False),
    sa.Column('scope', sa.Enum('CRITERION', 'EVALUATION', 'RUN', name='challengescope', native_enum=False, length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('observed', sa.JSON(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['evaluation_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_findings_check'), 'challenge_findings', ['check'], unique=False)
    op.create_index(op.f('ix_challenge_findings_criterion_id'), 'challenge_findings', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_challenge_findings_evaluation_id'), 'challenge_findings', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_challenge_findings_run_id'), 'challenge_findings', ['run_id'], unique=False)
    op.create_index(op.f('ix_challenge_findings_severity'), 'challenge_findings', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_challenge_findings_severity'), table_name='challenge_findings')
    op.drop_index(op.f('ix_challenge_findings_run_id'), table_name='challenge_findings')
    op.drop_index(op.f('ix_challenge_findings_evaluation_id'), table_name='challenge_findings')
    op.drop_index(op.f('ix_challenge_findings_criterion_id'), table_name='challenge_findings')
    op.drop_index(op.f('ix_challenge_findings_check'), table_name='challenge_findings')
    op.drop_table('challenge_findings')
    # ### end Alembic commands ###
