"""phase_d_evaluations_criteria_evidence_eligibility

Revision ID: 42eb3fd3b075
Revises: 4b653d768425
Create Date: 2026-09-10 13:36:22.607372

Phase D. Adds five tables and touches nothing from Phases A-C:

    evaluation_runs        one scoring run, pinned to a rubric version
    evaluations            one candidate's result, write-once
    evaluation_criteria    per-criterion score, outcome and confidence
    evaluation_evidence    quoted CV excerpts with page/section references
    eligibility_findings   deterministic disqualification-rule results

The downgrade drops all five. Because evaluations are the historical record
of hiring decisions, running it destroys audit history that cannot be
regenerated (the rubric version it was scored against may since have been
superseded). Take a database copy first.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42eb3fd3b075'
down_revision: Union[str, Sequence[str], None] = '707237c86d96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('reevaluation_of_run_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'CANCELLED', name='runstatus', native_enum=False, length=32), nullable=False),
    sa.Column('trigger', sa.Enum('MANUAL', 'BATCH_COMPLETION', 'REEVALUATION', name='runtrigger', native_enum=False, length=32), nullable=False),
    sa.Column('scoring_mode', sa.Enum('DETERMINISTIC', 'LLM_ASSISTED', name='scoringmode', native_enum=False, length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('total_candidates', sa.Integer(), nullable=False),
    sa.Column('evaluated_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['processing_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_runs_campaign_id'), 'evaluation_runs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_evaluation_runs_rubric_version_id'), 'evaluation_runs', ['rubric_version_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('COMPLETED', 'FAILED', 'SKIPPED', name='evaluationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('overall_confidence', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidenceband', native_enum=False, length=16), nullable=False),
    sa.Column('mandatory_score', sa.Float(), nullable=False),
    sa.Column('preferred_score', sa.Float(), nullable=False),
    sa.Column('eligibility_status', sa.Enum('ELIGIBLE', 'DISQUALIFIED', 'REVIEW_REQUIRED', name='eligibilitystatus', native_enum=False, length=32), nullable=False),
    sa.Column('recommendation', sa.Enum('STRONG_FIT', 'POTENTIAL_FIT', 'REVIEW_REQUIRED', 'NOT_RECOMMENDED', name='recommendation', native_enum=False, length=32), nullable=False),
    sa.Column('experience_years_total', sa.Float(), nullable=False),
    sa.Column('experience_years_relevant', sa.Float(), nullable=False),
    sa.Column('experience_profile', sa.JSON(), nullable=True),
    sa.Column('strengths', sa.JSON(), nullable=True),
    sa.Column('gaps', sa.JSON(), nullable=True),
    sa.Column('missing_information', sa.JSON(), nullable=True),
    sa.Column('contradictions', sa.JSON(), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('scoring_mode', sa.Enum('DETERMINISTIC', 'LLM_ASSISTED', name='scoringmode', native_enum=False, length=32), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['candidate_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'candidate_id', name='uq_evaluation_run_candidate')
    )
    op.create_index(op.f('ix_evaluations_campaign_id'), 'evaluations', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_evaluations_candidate_id'), 'evaluations', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_evaluations_eligibility_status'), 'evaluations', ['eligibility_status'], unique=False)
    op.create_index(op.f('ix_evaluations_is_current'), 'evaluations', ['is_current'], unique=False)
    op.create_index(op.f('ix_evaluations_recommendation'), 'evaluations', ['recommendation'], unique=False)
    op.create_index(op.f('ix_evaluations_rubric_version_id'), 'evaluations', ['rubric_version_id'], unique=False)
    op.create_index(op.f('ix_evaluations_run_id'), 'evaluations', ['run_id'], unique=False)
    op.create_table('eligibility_findings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('rule_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.Enum('MIN_YEARS_EXPERIENCE', 'MISSING_MANDATORY_SKILL', 'MISSING_QUALIFICATION', 'MISSING_CERTIFICATION', 'LOCATION_MISMATCH', 'ELIGIBILITY_FAILURE', 'MIN_CRITERION_SCORE', 'CUSTOM', name='ruletype', native_enum=False, length=48), nullable=False),
    sa.Column('operator', sa.Enum('LT', 'LTE', 'GT', 'GTE', 'EQ', 'NEQ', 'MISSING', 'PRESENT', 'IN', 'NOT_IN', name='ruleoperator', native_enum=False, length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.Enum('HARD_FAIL', 'REVIEW_REQUIRED', name='ruleseverity', native_enum=False, length=32), nullable=False),
    sa.Column('triggered', sa.Boolean(), nullable=False),
    sa.Column('observed_value', sa.Text(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('indeterminate', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['disqualification_rules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_findings_evaluation_id'), 'eligibility_findings', ['evaluation_id'], unique=False)
    op.create_index(op.f('ix_eligibility_findings_triggered'), 'eligibility_findings', ['triggered'], unique=False)
    op.create_table('evaluation_criteria',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('rubric_weight_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SKILL', 'EXPERIENCE', 'QUALIFICATION', 'CERTIFICATION', 'RESPONSIBILITY', 'INDUSTRY', 'FUNCTIONAL', 'SENIORITY', 'LOCATION', 'ELIGIBILITY', 'DIFFERENTIATING', name='requirementcategory', native_enum=False, length=32), nullable=False),
    sa.Column('requirement_type', sa.Enum('MANDATORY', 'PREFERRED', 'INFORMATIONAL', name='requirementtype', native_enum=False, length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('scoring_method', sa.Enum('WEIGHTED', 'BINARY', 'GRADED', name='scoringmethod', native_enum=False, length=32), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('weighted_score', sa.Float(), nullable=False),
    sa.Column('llm_adjusted', sa.Boolean(), nullable=False),
    sa.Column('outcome', sa.Enum('CONFIRMED_MATCH', 'PARTIAL_MATCH', 'NOT_DEMONSTRATED', 'CONTRADICTORY_EVIDENCE', 'INSUFFICIENT_EVIDENCE', name='criterionoutcome', native_enum=False, length=32), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confidence_band', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidenceband', native_enum=False, length=16), nullable=False),
    sa.Column('matched_terms', sa.JSON(), nullable=True),
    sa.Column('equivalent_terms', sa.JSON(), nullable=True),
    sa.Column('missing_terms', sa.JSON(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['rubric_weight_id'], ['rubric_weights.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'criterion_key', name='uq_evaluation_criterion_key')
    )
    op.create_index(op.f('ix_evaluation_criteria_criterion_key'), 'evaluation_criteria', ['criterion_key'], unique=False)
    op.create_index(op.f('ix_evaluation_criteria_evaluation_id'), 'evaluation_criteria', ['evaluation_id'], unique=False)
    op.create_table('evaluation_evidence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=True),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=64), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('match_type', sa.Enum('EXACT', 'EQUIVALENT', 'CONTRADICTION', 'CONTEXT', name='evidencematchtype', native_enum=False, length=32), nullable=False),
    sa.Column('matched_term', sa.String(length=255), nullable=False),
    sa.Column('relevance', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criterion_id'], ['evaluation_criteria.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_id'], ['candidate_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_evidence_criterion_id'), 'evaluation_evidence', ['criterion_id'], unique=False)
    op.create_index(op.f('ix_evaluation_evidence_evaluation_id'), 'evaluation_evidence', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluation_evidence_evaluation_id'), table_name='evaluation_evidence')
    op.drop_index(op.f('ix_evaluation_evidence_criterion_id'), table_name='evaluation_evidence')
    op.drop_table('evaluation_evidence')
    op.drop_index(op.f('ix_evaluation_criteria_evaluation_id'), table_name='evaluation_criteria')
    op.drop_index(op.f('ix_evaluation_criteria_criterion_key'), table_name='evaluation_criteria')
    op.drop_table('evaluation_criteria')
    op.drop_index(op.f('ix_eligibility_findings_triggered'), table_name='eligibility_findings')
    op.drop_index(op.f('ix_eligibility_findings_evaluation_id'), table_name='eligibility_findings')
    op.drop_table('eligibility_findings')
    op.drop_index(op.f('ix_evaluations_run_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_rubric_version_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_recommendation'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_is_current'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_eligibility_status'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_candidate_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_campaign_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_evaluation_runs_rubric_version_id'), table_name='evaluation_runs')
    op.drop_index(op.f('ix_evaluation_runs_campaign_id'), table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    # ### end Alembic commands ###
