"""phase_c_candidates_documents_batches_jobs

Revision ID: 4b653d768425
Revises: 63d33e3e05be
Create Date: 2026-09-10 08:47:40.531877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b653d768425'
down_revision: Union[str, Sequence[str], None] = '63d33e3e05be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('email_normalized', sa.String(length=320), nullable=False),
    sa.Column('phone_normalized', sa.String(length=32), nullable=False),
    sa.Column('name_normalized', sa.String(length=255), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_campaign_id'), 'candidates', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_candidates_email_normalized'), 'candidates', ['email_normalized'], unique=False)
    op.create_index(op.f('ix_candidates_name_normalized'), 'candidates', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_candidates_phone_normalized'), 'candidates', ['phone_normalized'], unique=False)
    op.create_table('candidate_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('extension', sa.String(length=16), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('text_char_count', sa.Integer(), nullable=False),
    sa.Column('section_map', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_documents_campaign_id'), 'candidate_documents', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_candidate_id'), 'candidate_documents', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_documents_content_hash'), 'candidate_documents', ['content_hash'], unique=False)
    op.create_table('processing_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'COMPLETED_WITH_ERRORS', 'CANCELLED', name='batchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_batches_campaign_id'), 'processing_batches', ['campaign_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'DUPLICATE', 'CANCELLED', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('error_code', sa.Enum('UNSUPPORTED_FORMAT', 'EMPTY_FILE', 'FILE_TOO_LARGE', 'CORRUPT_FILE', 'PASSWORD_PROTECTED', 'NO_TEXT_EXTRACTED', 'INCOMPLETE_CONTENT', 'EXTRACTION_FAILED', 'STORAGE_FAILED', 'INTERNAL_ERROR', name='joberrorcode', native_enum=False, length=40), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('duplicate_type', sa.Enum('EXACT_FILE', 'SAME_CANDIDATE_EMAIL', 'SAME_CANDIDATE_PHONE', 'SAME_CANDIDATE_NAME', name='duplicatetype', native_enum=False, length=32), nullable=True),
    sa.Column('duplicate_of_document_id', sa.String(length=36), nullable=True),
    sa.Column('duplicate_of_candidate_id', sa.String(length=36), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['processing_batches.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['candidate_documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processing_jobs_batch_id'), 'processing_jobs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_campaign_id'), 'processing_jobs', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_status'), 'processing_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processing_jobs_status'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_campaign_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_batch_id'), table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_processing_batches_campaign_id'), table_name='processing_batches')
    op.drop_table('processing_batches')
    op.drop_index(op.f('ix_candidate_documents_content_hash'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_candidate_id'), table_name='candidate_documents')
    op.drop_index(op.f('ix_candidate_documents_campaign_id'), table_name='candidate_documents')
    op.drop_table('candidate_documents')
    op.drop_index(op.f('ix_candidates_phone_normalized'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_name_normalized'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_email_normalized'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_campaign_id'), table_name='candidates')
    op.drop_table('candidates')
    # ### end Alembic commands ###
