"""phase_f_candidate_actions_audit_rollups

Revision ID: 4f28eb855061
Revises: 1e9e5fabd527
Create Date: 2026-09-10 18:13:42.056044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f28eb855061'
down_revision: Union[str, Sequence[str], None] = '1e9e5fabd527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.Enum('CAMPAIGN_CREATED', 'CAMPAIGN_STATUS_CHANGED', 'REQUIREMENTS_EXTRACTED', 'RUBRIC_VERSION_CREATED', 'RUBRIC_SUBMITTED', 'RUBRIC_APPROVED', 'RUBRIC_REJECTED', 'RUBRIC_LOCKED', 'BATCH_UPLOADED', 'EVALUATION_RUN_STARTED', 'EVALUATION_RUN_COMPLETED', 'REEVALUATION_STARTED', 'DISPOSITION_SET', 'RECOMMENDATION_OVERRIDDEN', 'COMMENT_ADDED', 'EXPORTED', name='auditaction', native_enum=False, length=40), nullable=False),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_campaign_id'), 'audit_events', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('candidate_actions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('candidate_id', sa.String(length=36), nullable=False),
    sa.Column('evaluation_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.Enum('COMMENT', 'DISPOSITION', 'OVERRIDE', name='actiontype', native_enum=False, length=24), nullable=False),
    sa.Column('disposition', sa.Enum('SHORTLIST', 'REJECT', 'HOLD', 'REQUEST_REVIEW', 'INTERVIEW', name='disposition', native_enum=False, length=24), nullable=True),
    sa.Column('ai_recommendation', sa.Enum('STRONG_FIT', 'POTENTIAL_FIT', 'REVIEW_REQUIRED', 'NOT_RECOMMENDED', name='recommendation', native_enum=False, length=32), nullable=True),
    sa.Column('overridden_to', sa.Enum('STRONG_FIT', 'POTENTIAL_FIT', 'REVIEW_REQUIRED', 'NOT_RECOMMENDED', name='recommendation', native_enum=False, length=32), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('actor_role', sa.String(length=64), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('superseded_by_action_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_actions_action_type'), 'candidate_actions', ['action_type'], unique=False)
    op.create_index(op.f('ix_candidate_actions_campaign_id'), 'candidate_actions', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_candidate_actions_candidate_id'), 'candidate_actions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_actions_disposition'), 'candidate_actions', ['disposition'], unique=False)
    op.create_index(op.f('ix_candidate_actions_is_current'), 'candidate_actions', ['is_current'], unique=False)
    op.add_column('evaluations', sa.Column('skills_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('experience_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('education_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('certification_score', sa.Float(), nullable=True))
    op.add_column('evaluations', sa.Column('category_scores', sa.JSON(), nullable=True))
    op.add_column('evaluations', sa.Column('next_action', sa.Enum('INTERVIEW', 'MANUAL_REVIEW', 'REQUEST_EVIDENCE', 'CONFIRM_ELIGIBILITY', 'REJECT', name='nextaction', native_enum=False, length=32), nullable=True))
    op.add_column('evaluations', sa.Column('next_action_reason', sa.Text(), nullable=False))
    op.add_column('evaluations', sa.Column('validation_questions', sa.JSON(), nullable=True))
    op.add_column('evaluations', sa.Column('interview_focus', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('evaluations', 'interview_focus')
    op.drop_column('evaluations', 'validation_questions')
    op.drop_column('evaluations', 'next_action_reason')
    op.drop_column('evaluations', 'next_action')
    op.drop_column('evaluations', 'category_scores')
    op.drop_column('evaluations', 'certification_score')
    op.drop_column('evaluations', 'education_score')
    op.drop_column('evaluations', 'experience_score')
    op.drop_column('evaluations', 'skills_score')
    op.drop_index(op.f('ix_candidate_actions_is_current'), table_name='candidate_actions')
    op.drop_index(op.f('ix_candidate_actions_disposition'), table_name='candidate_actions')
    op.drop_index(op.f('ix_candidate_actions_candidate_id'), table_name='candidate_actions')
    op.drop_index(op.f('ix_candidate_actions_campaign_id'), table_name='candidate_actions')
    op.drop_index(op.f('ix_candidate_actions_action_type'), table_name='candidate_actions')
    op.drop_table('candidate_actions')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_campaign_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
