"""phase_b_rubric_weights_disqualification_versioning

Revision ID: 63d33e3e05be
Revises: 92eec49b510e
Create Date: 2026-09-10 08:25:23.864566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63d33e3e05be'
down_revision: Union[str, Sequence[str], None] = '92eec49b510e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rubrics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_campaign_id'), 'rubrics', ['campaign_id'], unique=True)
    op.create_table('rubric_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rubric_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'LOCKED', 'REJECTED', 'SUPERSEDED', name='rubricstatus', native_enum=False, length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('cloned_from_version_id', sa.String(length=36), nullable=True),
    sa.Column('supersedes_version_id', sa.String(length=36), nullable=True),
    sa.Column('reevaluation_required', sa.Boolean(), nullable=False),
    sa.Column('reevaluation_acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('reevaluation_acknowledged_by', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('submitted_by', sa.String(length=255), nullable=False),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('rejected_by', sa.String(length=255), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_id', 'version_number', name='uq_rubric_version_number')
    )
    op.create_index(op.f('ix_rubric_versions_rubric_id'), 'rubric_versions', ['rubric_id'], unique=False)
    op.create_table('disqualification_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('rule_type', sa.Enum('MIN_YEARS_EXPERIENCE', 'MISSING_MANDATORY_SKILL', 'MISSING_QUALIFICATION', 'MISSING_CERTIFICATION', 'LOCATION_MISMATCH', 'ELIGIBILITY_FAILURE', 'MIN_CRITERION_SCORE', 'CUSTOM', name='ruletype', native_enum=False, length=48), nullable=False),
    sa.Column('operator', sa.Enum('LT', 'LTE', 'GT', 'GTE', 'EQ', 'NEQ', 'MISSING', 'PRESENT', 'IN', 'NOT_IN', name='ruleoperator', native_enum=False, length=16), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('severity', sa.Enum('HARD_FAIL', 'REVIEW_REQUIRED', name='ruleseverity', native_enum=False, length=32), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['job_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disqualification_rules_rubric_version_id'), 'disqualification_rules', ['rubric_version_id'], unique=False)
    op.create_table('rubric_weights',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('rubric_version_id', sa.String(length=36), nullable=False),
    sa.Column('requirement_id', sa.String(length=36), nullable=True),
    sa.Column('criterion_key', sa.String(length=128), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SKILL', 'EXPERIENCE', 'QUALIFICATION', 'CERTIFICATION', 'RESPONSIBILITY', 'INDUSTRY', 'FUNCTIONAL', 'SENIORITY', 'LOCATION', 'ELIGIBILITY', 'DIFFERENTIATING', name='requirementcategory', native_enum=False, length=32), nullable=False),
    sa.Column('requirement_type', sa.Enum('MANDATORY', 'PREFERRED', 'INFORMATIONAL', name='requirementtype', native_enum=False, length=32), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('scoring_method', sa.Enum('WEIGHTED', 'BINARY', 'GRADED', name='scoringmethod', native_enum=False, length=32), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['job_requirements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rubric_version_id'], ['rubric_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rubric_version_id', 'criterion_key', name='uq_rubric_weight_criterion')
    )
    op.create_index(op.f('ix_rubric_weights_rubric_version_id'), 'rubric_weights', ['rubric_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rubric_weights_rubric_version_id'), table_name='rubric_weights')
    op.drop_table('rubric_weights')
    op.drop_index(op.f('ix_disqualification_rules_rubric_version_id'), table_name='disqualification_rules')
    op.drop_table('disqualification_rules')
    op.drop_index(op.f('ix_rubric_versions_rubric_id'), table_name='rubric_versions')
    op.drop_table('rubric_versions')
    op.drop_index(op.f('ix_rubrics_campaign_id'), table_name='rubrics')
    op.drop_table('rubrics')
    # ### end Alembic commands ###
