"""phase_a_campaign_and_job_requirements

Revision ID: 92eec49b510e
Revises: 
Create Date: 2026-09-10 07:48:19.800609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92eec49b510e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('vacancies', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('business_unit', sa.String(length=255), nullable=False),
    sa.Column('recruiter', sa.String(length=255), nullable=False),
    sa.Column('hiring_manager', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('target_completion_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AWAITING_RUBRIC_APPROVAL', 'APPROVED', 'PROCESSING', 'REVIEW', 'CLOSED', name='campaignstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('SKILL', 'EXPERIENCE', 'QUALIFICATION', 'CERTIFICATION', 'RESPONSIBILITY', 'INDUSTRY', 'FUNCTIONAL', 'SENIORITY', 'LOCATION', 'ELIGIBILITY', 'DIFFERENTIATING', name='requirementcategory', native_enum=False, length=32), nullable=False),
    sa.Column('requirement_type', sa.Enum('MANDATORY', 'PREFERRED', 'INFORMATIONAL', name='requirementtype', native_enum=False, length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('disqualifying', sa.Boolean(), nullable=False),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_campaign_id'), 'job_requirements', ['campaign_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_requirements_campaign_id'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
